/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/stock-inventories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a stock inventory by id */
        get: operations["findById"];
        /** Update an existing stock inventory */
        put: operations["update"];
        post?: never;
        /** Delete a stock inventory */
        delete: operations["deleteById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a project by its id */
        get: operations["findById_1"];
        /** Update an existing project */
        put: operations["update_1"];
        post?: never;
        /** Delete a project */
        delete: operations["deleteById_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/production-days/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a production day by id */
        get: operations["findById_2"];
        /** Update a production day */
        put: operations["update_2"];
        post?: never;
        /** Delete a production day */
        delete: operations["deleteById_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find an operation by id */
        get: operations["findById_3"];
        /** Update an existing operation */
        put: operations["update_3"];
        post?: never;
        /** Delete an operation */
        delete: operations["deleteById_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find an investor by id */
        get: operations["findById_4"];
        /** Update an existing investor */
        put: operations["update_4"];
        post?: never;
        /** Delete an investor */
        delete: operations["deleteById_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capital-distributions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a capital distribution by id */
        get: operations["findById_5"];
        /** Update an existing capital distribution */
        put: operations["update_5"];
        post?: never;
        /** Delete a capital distribution */
        delete: operations["deleteById_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock-inventories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all stock inventories */
        get: operations["findAll"];
        put?: never;
        /** Create a new stock inventory */
        post: operations["save"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all projects owned by the authenticated user */
        get: operations["findAll_1"];
        put?: never;
        /** Create a new project linked to the authenticated user */
        post: operations["save_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/production-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all production days */
        get: operations["findAll_2"];
        put?: never;
        /** Record a new production day */
        post: operations["save_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all operations */
        get: operations["findAll_3"];
        put?: never;
        /** Create a new financial operation */
        post: operations["save_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/investors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all investors */
        get: operations["findAll_4"];
        put?: never;
        /** Create a new investor */
        post: operations["save_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capital-distributions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve all capital distributions */
        get: operations["findAll_5"];
        put?: never;
        /** Create a new capital distribution */
        post: operations["save_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user's info from the Firebase token */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Project stock inventory */
        StockInventoryDto: {
            /**
             * Format: int64
             * @description Inventory identifier
             * @example 1
             */
            readonly id?: number;
            /** @description List of items in stock */
            items?: components["schemas"]["StockItemDto"][];
        };
        /** @description Stock item */
        StockItemDto: {
            /**
             * @description Item name
             * @example Fertilizer bag
             */
            name: string;
            /**
             * Format: int32
             * @description Quantity in stock
             * @example 150
             */
            quantity: number;
            /**
             * @description Unit of measure
             * @example kg
             */
            unit: string;
        };
        /** @description Financial operation (income or expense) */
        OperationDto: {
            /**
             * Format: int64
             * @description Operation identifier
             * @example 1
             */
            readonly id?: number;
            /**
             * @description Operation label
             * @example Seed purchase
             */
            label: string;
            /**
             * Format: date
             * @description Operation date
             * @example 2025-04-10
             */
            date: string;
            /**
             * Format: double
             * @description Operation amount
             * @example 1500
             */
            amount: number;
            /**
             * @description Operation type: INCOME or EXPENSE
             * @example EXPENSE
             * @enum {string}
             */
            operationType: "INCOME" | "EXPENSE";
        };
        /** @description Daily production record */
        ProductionDayDto: {
            /**
             * Format: int64
             * @description Production day identifier
             * @example 1
             */
            readonly id?: number;
            /**
             * Format: date
             * @description Production date
             * @example 2025-04-15
             */
            date: string;
            /**
             * Format: int32
             * @description Quantity produced on that day
             * @example 120
             */
            quantity: number;
        };
        /** @description Project financial capital */
        ProjectCapitalDto: {
            /**
             * Format: double
             * @description Initial capital invested
             * @example 100000
             */
            initialCapital?: number;
            /**
             * Format: double
             * @description Currently available capital
             * @example 75000
             */
            currentCapital?: number;
            /**
             * Format: double
             * @description Total investments made
             * @example 120000
             */
            totalInvestment?: number;
            /**
             * Format: double
             * @description Total expenses incurred
             * @example 45000
             */
            totalExpenses?: number;
        };
        /** @description Agricultural or livestock project */
        ProjectDto: {
            /**
             * Format: int64
             * @description Project identifier
             * @example 1
             */
            readonly id?: number;
            /** @description Firebase UID of the project owner */
            readonly ownerUid?: string;
            /**
             * @description Project name
             * @example Corn Farm 2025
             */
            name?: string;
            /**
             * @description Project type
             * @example AGRICULTURE
             * @enum {string}
             */
            projectType: "AGRICULTURE" | "LIVESTOCK";
            /**
             * @description Livestock type (only for LIVESTOCK projects)
             * @example CHICKEN
             * @enum {string}
             */
            livestockType?: "PIG" | "CHICKEN" | "RABBIT";
            /** @description Project resources */
            resources?: components["schemas"]["ProjectResourcesDto"];
            /** @description Project financial capital */
            capital?: components["schemas"]["ProjectCapitalDto"];
            /** @description Production and profitability statistics */
            statistics?: components["schemas"]["ProjectStatisticsDto"];
            /** @description Recorded production days */
            productions?: components["schemas"]["ProductionDayDto"][];
            /** @description Financial operations of the project */
            operations?: components["schemas"]["OperationDto"][];
        };
        /** @description Project resources */
        ProjectResourcesDto: {
            /**
             * Format: double
             * @description Initial budget allocated to the project
             * @example 50000
             */
            budget?: number;
            /**
             * Format: double
             * @description Land size in hectares
             * @example 2.5
             */
            landSize?: number;
            /**
             * @description Whether existing structures are present on the land
             * @example true
             */
            existingStructures?: boolean;
            /**
             * @description Additional notes
             * @example Fenced land with a well
             */
            notes?: string;
        };
        /** @description Project production and profitability statistics */
        ProjectStatisticsDto: {
            /**
             * Format: double
             * @description Cumulative total production (units)
             * @example 3500
             */
            totalProduction?: number;
            /**
             * Format: double
             * @description Total revenue generated
             * @example 85000
             */
            totalRevenue?: number;
            /**
             * Format: double
             * @description Total net profit
             * @example 40000
             */
            totalProfit?: number;
            /**
             * Format: double
             * @description Productivity rate as a percentage
             * @example 78.5
             */
            productivityRate?: number;
        };
        /** @description Project investor */
        InvestorDto: {
            /**
             * Format: int64
             * @description Investor identifier
             * @example 1
             */
            readonly id?: number;
            /**
             * @description Full name of the investor
             * @example Marie Curie
             */
            fullName: string;
            /**
             * Format: double
             * @description Financial contribution amount
             * @example 25000
             */
            contribution: number;
        };
        /** @description Capital distribution among investors */
        CapitalDistributionDto: {
            /**
             * Format: int64
             * @description Distribution identifier
             * @example 1
             */
            readonly id?: number;
            /** @description List of shares per investor (total must equal 100%) */
            shares?: components["schemas"]["CapitalShareDto"][];
        };
        /** @description Capital share of an investor */
        CapitalShareDto: {
            /**
             * @description Investor name
             * @example John Smith
             */
            investorName: string;
            /**
             * Format: double
             * @description Participation percentage (0-100)
             * @example 35
             */
            percentage: number;
        };
        /** @description Request payload to create a new project */
        CreateProjectRequest: {
            /**
             * @description Project name
             * @example Corn Farm 2025
             */
            name: string;
            /**
             * @description Project type
             * @example LIVESTOCK
             * @enum {string}
             */
            projectType: "AGRICULTURE" | "LIVESTOCK";
            /**
             * @description Livestock type — required when projectType is LIVESTOCK
             * @example CHICKEN
             * @enum {string}
             */
            livestockType?: "PIG" | "CHICKEN" | "RABBIT";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stock inventory identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock inventory found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StockInventoryDto"];
                };
            };
            /** @description Stock inventory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stock inventory identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockInventoryDto"];
            };
        };
        responses: {
            /** @description Stock inventory updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StockInventoryDto"];
                };
            };
            /** @description Stock inventory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Stock inventory identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock inventory deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stock inventory not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectDto"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production day identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Production day found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductionDayDto"];
                };
            };
            /** @description Production day not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production day identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionDayDto"];
            };
        };
        responses: {
            /** @description Production day updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductionDayDto"];
                };
            };
            /** @description Production day not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Production day identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Production day deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Production day not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Operation identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationDto"];
                };
            };
            /** @description Operation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Operation identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationDto"];
            };
        };
        responses: {
            /** @description Operation updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationDto"];
                };
            };
            /** @description Operation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Operation identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operation deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Operation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Investor identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investor found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvestorDto"];
                };
            };
            /** @description Investor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Investor identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorDto"];
            };
        };
        responses: {
            /** @description Investor updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvestorDto"];
                };
            };
            /** @description Investor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteById_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Investor identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investor deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Investor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Capital distribution identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capital distribution found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapitalDistributionDto"];
                };
            };
            /** @description Capital distribution not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Capital distribution identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapitalDistributionDto"];
            };
        };
        responses: {
            /** @description Capital distribution updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapitalDistributionDto"];
                };
            };
            /** @description Capital distribution not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteById_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Capital distribution identifier */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capital distribution deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Capital distribution not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of stock inventories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StockInventoryDto"][];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockInventoryDto"];
            };
        };
        responses: {
            /** @description Stock inventory created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StockInventoryDto"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDto"][];
                };
            };
        };
    };
    save_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProjectDto"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of production days */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductionDayDto"][];
                };
            };
        };
    };
    save_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductionDayDto"];
            };
        };
        responses: {
            /** @description Production day created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductionDayDto"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of operations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationDto"][];
                };
            };
        };
    };
    save_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationDto"];
            };
        };
        responses: {
            /** @description Operation created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperationDto"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of investors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvestorDto"][];
                };
            };
        };
    };
    save_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvestorDto"];
            };
        };
        responses: {
            /** @description Investor created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InvestorDto"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of capital distributions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapitalDistributionDto"][];
                };
            };
        };
    };
    save_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapitalDistributionDto"];
            };
        };
        responses: {
            /** @description Capital distribution created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CapitalDistributionDto"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
}
